version: 2

models:
  - name: stg_raw__stock
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
      - name: color
        tests:
          - dbt_utils.not_accepted_values:
              values: ['BL', 'RD']
