version: 2

sources:
  - name: raw
    schema: raw_data_circle
    tables:
      - name: sales
        identifier: raw_cc_sales
        columns:
          - name: date_date
            tests:
              - not_null
          - name: product_id
            tests:
              - not_null
          - name: quantity
        tests:
          - unique:
              column_name: "date_date || product_id"
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - date_date
                - product_id
      - name: stock
        identifier: raw_cc_stock
        tests:
          - unique:
              column_name: "model || color || size"
      - name: parcel
        identifier: raw_cc_parcel
      - name: parcel_product
        identifier: raw_cc_parcel_product
